application: hand-ratio
version: 2
runtime: python27
api_version: 1
threadsafe: yes
module: default

handlers:
- url: /index
  script: main.app
  
- url: /static
  static_dir: static_files
  
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest